version: '2'
services:
  web:
    build:
      dockerfile: Dockerfile
    ports:
      - 10001:10001
      - 11619:11619
    environment:
      ## JVM SETTINGS
      - JVM_MEMORY=-Xms1g -Xmx1g
      - SPRING_PROFILE=develop
    volumes:
      - ~/n2n/app-log:/n2n/app-log
      - ~/n2n/gc-log:/n2n/gc-log
#    privileged: true # if manipulation necessary